### ISSUE TITLE
اضافه کردن سایر الگوریتم های فراابتکاری

### ISSUE THREAD

**Issue by soheilre** [AmiraliOmidvar/ga_hypertuner#1]
با سلام و وقت بخیر جناب امیدوار عزیز
خسته نباشید

تشکر بابت انتشار این کتابخانه بسیار مفید و کاربردی

یک سوالی از خدمتتون داشتم

امکان اضافه کردن سایر الگوریتم ها مانند زنبور عسل، گرگ خاکستری و ... به این کتابخانه وجود دارد؟ یا اینکه راهنمایی بفرمایید روند کلی اضافه کردن الگوریتم دلخواه به چه صورت می تواند باشد که خود من بتوانم انجام بدهم؟

با تشکر از شما

موفق باشید

**Comment by AmiraliOmidvar** [comment]
با سلام و درود.
ممنون از شما و خوشحالم که این کتابخانه مفید واقع شده.
در مورد اضافه کردن الگوریتم های فراابتکاری دیگر:
در کل ماژول های این کتابخانه حول الگوریتم ژنتیکی نوشته شده اند، مخصوصا خود قسمت آپتیمیزیشن کاملا از پایه براساس همین الگوریتم هست و ماژول کمکی نداره.
اما امکان اضافه کردن الگوریتم‌های دیگر هست به نظرم اگر این مراحل را طی کنید کارتان راحت تر خواهد بود.
1- پارامترهای ورودی متود اصلی که tune هست در ماژول tuner تغییر بدید تا پارامترهایی که نیاز دارید را از یوزر دریافت کنید.
2- اکسپشن های مورد نظر را که در متد _check_ga_params هست (همان ماژول tuner) را تغییر دهید یا حذف کنید. (در حال حاضر پارامترهای الگورتیم ژنتیکی را چک می‌کند.)
3 - الگوریتم مورد نظر خود را در یک ماژول جدا بنویسید. احتمالا این الگوریتم‌ها تفاوت زیادی با الگوریتم ژنتیکی از نظر استراکچر ندارند و برحسب ایتریشن جمعیت هستند. می توانید متدهای ماژول ga را برای رفرنس ببینید. به خصوص نحوه امیتاز دهی را میتوانید مستقیما استفاده کنید در الگوریتم خودتان.
4- از ماژول های reporting و visualization هم به راحتی می‌توانید استفاده کنید چون داده پراسس شده دریافت می کنند. 
امیدوارم این توضیحات مفید واقع شده باشه و اگر سوال دیگری بود در خدمت هستم.

Hello and greetings.

Thank you for your kind words and I'm glad that you find this library useful.

Regarding adding other metaheuristic algorithms:
The modules in this library are mostly centered around the genetic algorithm, especially the optimization module, which is completely based on this algorithm and doesn't have any helper modules.

However, it's possible to add other algorithms to the library. Here are the steps that can make it easier:

1- Modify the input parameters of the main method, which is "tune" in the "tuner" module, to receive the parameters you need from the user.

2- Modify or remove the relevant exceptions in the "_check_ga_params" method (in the "tuner" module). (Currently, it checks the parameters of the genetic algorithm.)

3- Write your own algorithm in a separate module. These algorithms probably don't have much difference in structure from the genetic algorithm and are based on iterations of the population. You can refer to the methods in the ga module, especially the way of scoring, which you can use directly in your own algorithm.

4- You can easily use the "reporting" and "visualization" modules as well, as they receive processed data.

I hope these explanations are helpful and if you have any other questions, I'm here to help.

**Comment by soheilre** [comment]
تشکر از پاسخ تون
خیلی لطف کردید
اگر سوالی بود مجدد مزاحم خواهم بود
موفق باشید
